Demar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('plitki/',views.plitki,name='plitki'),
    path('gallery/',views.gallery,name='gallery'),
    path('cart/',views.cart,name='cart'),
    path('laminat/',views.laminat,name='laminat'),
    path('cart-create/',views.cart_create,name='cart_create'),
    path('cart-update/',views.cart_update,name='cart_update'),
    path('cart-delete/',views.cart_delete,name='cart_delete'),
    path("order/", views.order, name="order"),
    path("orderview/", views.orderView, name="orderview"),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	name = models.CharField('Ismi',max_length=250,)
	phone = models.CharField('Telefon ', max_length=50)
	message = models.CharField('Xabari', max_length=250)

	class Meta:
		verbose_name = 'Savol'
		verbose_name_plural = 'Savollar'

	def __str__(self):
		return f"{self.name}"
class Contact(models.Model):
	name = models.CharField('Ismi',max_length=250,)
	phone = models.CharField('Telefon ', max_length=50)
	email = models.EmailField('Emaili', max_length=250)

	class Meta:
		verbose_name = 'Aloqa'
		verbose_name_plural = 'Aloqalar'

	def __str__(self):
		return f"{self.name}"


class Category(models.Model):
    name = models.CharField('Nomi',max_length=150,)
    slug = models.SlugField('*',max_length=150, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_detail', kwargs={'category_slug':self.slug})

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    color = models.CharField('Rangi',max_length=200)
    image = models.ImageField(upload_to='product_images/',blank=True)
    description = models.TextField(blank=True)
    price = models.FloatField()
    old_price = models.PositiveIntegerField('Avvalgi Narxi',default=0)
    available = models.BooleanField(default=True)
    instock = models.BooleanField('Bor / Yok', default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail',args=[str(self.slug)])


class Cart(models.Model):
    product = models.ForeignKey("main.Product", verbose_name="cart of product", on_delete=models.CASCADE)
    mkv = models.FloatField("m kvadrat")
    all_price = models.FloatField()

    def __str__(self):
        return f"{self.product.name}, --{self.mkv}"


class MainCart(models.Model):
    carts =  models.ManyToManyField(Cart, verbose_name="carts", blank=True)
    all_price = models.FloatField(default=0)

    def __str__(self):
        return str(self.carts.all().count())


class Order(models.Model):
    first_name = models.CharField("Ismi", max_length=50)
    last_name = models.CharField("familiyasi", max_length=50)
    phone = models.PositiveIntegerField("phone")
    cart = models.ForeignKey(MainCart, verbose_name="carts", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name}, {self.last_name}"

main/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render,redirect
from .models import *
from django.contrib import messages
from django.template import RequestContext
from django.http import JsonResponse, request
from django.contrib.auth.models import User

def index(request):
	products = Product.objects.all().order_by('-id')
	if request.method == 'POST':
		name = request.POST['name']
		phone = request.POST['phone']
		message = request.POST['message']
		Question.objects.create(name=name,phone=phone,message=message)	
	return render(request,'index.html',{'products':products})

def contact(request):
	if request.method == 'POST':
		name = request.POST['name']
		phone = request.POST['phone']
		email = request.POST['email']
		Contact.objects.create(name=name,phone=phone,email=email)	
	return render(request,'contact.html')

def cart(request):
	
	main = request.session['cart']
	cart = get_object_or_404(MainCart, id=int(main))
	context = {
		'cart':cart,
	}
	return render(request,'cart.html', context)

def plitki(request):
	products = Product.objects.all().order_by('-id')
	return render(request,'catalogStone.html',{'products':products})
def about(request):
	return render(request,'about.html')
def laminat(request):
	products = Product.objects.all().order_by('-id')
	return render(request,'catalogLaminat.html',{'products':products})

def gallery(request):
	return render(request,'gallery.html')

# cart block

def mainCartCreate(request):
	try:
		print(request.session['cart'])
	except:
		cart = MainCart.objects.create()
		request.session['cart'] = cart.id
		print('cart created')

	return request


def cart_create(request):
	main = request.session['cart']
	product_id = request.GET.get('product_id')
	mkv = request.GET.get('mkv')
	product = Product.objects.get(id=product_id)
	all_price = float(mkv)*float(product.price)
	new = Cart.objects.create(
		product=product,
		mkv=float(mkv),
		all_price=all_price
	)
	mainCart = MainCart.objects.get(id=main)
	if new not in mainCart.carts.all():
		mainCart.carts.add(new)
		a = 0.0
		for i in mainCart.carts.all():
			a += i.all_price
		mainCart.all_price = a
		mainCart.save()
	return JsonResponse({'data':'created'})

def cart_update(request):
	main = request.session['cart']
	mkv = request.GET.get('mkv')
	cart_id = request.GET.get('cart_id')
	cart = Cart.objects.get(id=int(cart_id))
	price = cart.product.price*float(mkv)
	cart.all_price = price
	cart.mkv = mkv
	cart.save()
	mainCart = MainCart.objects.get(id=main)
	a = 0.0
	for i in mainCart.carts.all():
		a += i.all_price
	mainCart.all_price = a
	mainCart.save()
	return JsonResponse({
		'price':cart.all_price,
		'main_price':mainCart.all_price
		})

def cart_delete(request):
	main = request.session['cart']
	cart_id = request.GET.get('cart_id')
	cart = Cart.objects.get(id=int(cart_id))
	cart.delete()
	mainCart = MainCart.objects.get(id=main)
	a = 0.0
	for i in mainCart.carts.all():
		a += i.all_price
	mainCart.all_price = a
	mainCart.save()
	return JsonResponse({'main_price':mainCart.all_price})




import telebot
TOKEN = '5140670124:AAE4vNcnkQ9woUmBEOO3dJBQBZeoy_m0b0c'
chat_id = 1614757564
tb = telebot.TeleBot(TOKEN)


def order(request):
	main = request.session['cart']
	mainCart = MainCart.objects.get(id=main)
	name = request.GET.get('name')
	surname = request.GET.get('surname')
	phone = request.GET.get('phone')
	if mainCart.carts:
		order = Order.objects.create(
			first_name=name,
			last_name=surname,
			phone=int(phone),
			cart=mainCart
		)
		message = f"Ismi: {order.first_name}\nFamiliyasi: {order.last_name}\nTelefon raqami: {order.phone}\nTovarlar: \n"
		for i in order.cart.carts.all():
			message += f"{i}m kvadrat\n"
		message += f"Jami narxi: {order.cart.all_price} so'm"
		tb.send_message(chat_id, message)
	return redirect('/orderview/')


def orderView(request):
	return render(request, 'order.html')

templates/about.html
<!DOCTYPE html>
{% load static %}
{% block content %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="/static/fontawesome-free-5.15.4-web/css/all.min.css"
      rel="stylesheet"
    />
    <script
      src="tps://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
      integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <title>Demar</title>
    <link rel="stylesheet" href="/static/css/style.css" />
    <link
      rel="stylesheet"
      type="text/css"
      href="http://kenwheeler.github.io/slick/slick/slick-theme.css"
    />
  </head>
  <body>
    <div class="main">
      <header id="navbar">
       <a href="{% url 'main:index' %}"><img class="logo" src="/static/images/logo.png" alt="" /></a> 
        <div class="btn-hamburger" id="burger">
          <div id="drop-men" class="dropdown">
            <a data-toggle="dropdown"><i class="fas fa-bars"></i></a>
            <ul
              style="background-color: black; margin-left: -10px"
              id="drop-menu"
              class="dropdown-menu"
              role="menu"
              aria-labelledby="dLabel"
            >
              <div class="dropdow">
                <li><a href="{% url 'main:contact' %}">Контакты</a></li>
              </div><div class="dropdow">
                <li><a href="{% url 'main:about' %}">О нас</a></li>
              </div>
              <hr />
              <div class="dropdow">
                <li><a href="{% url 'main:gallery' %}">Галерея</a></li>
              </div>
            </ul>
          </div>
        </div>
        <ul class="header" id="ul">
          <li><a href="{% url 'main:contact' %}">Контакты</a></li>
          <li><a href="{% url 'main:gallery' %}">Галерея</a></li>
          <li><a href="{% url 'main:about' %}"> О нас</a></li>

        </ul>
        <div class="li-cen">
          <li class="glry">
            <div class="dropdown">
              <a style="color: #fff;"class="dropdown-toggle" data-toggle="dropdown">Каталог</a>
              <ul
                id="dropdown-menu"
                class="dropdown-menu"
                role="menu"
                aria-labelledby="dLabel"
              >
                <div class="dropdowns">
                  <h1 class="stoness"><a style="color: black;" href="{% url 'main:plitki' %}">Плитки</a></h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/stones.png"
                    alt=""
                  />
                </div>
                <hr class="hri" />
                <div class="dropdowns">
                  <h1 class="laminate">
                    <a style="color: black;" href="{% url 'main:laminat' %}">Кафель</a>
                  </h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/laminates.png"
                    alt=""
                  />
                </div>
              </ul>
            </div>
          </li>
        </div>
        <div class="navbar-end">
     
          <a href="{% url 'main:cart' %}"
            ><img class="cart" src="/static/images/cart.png" alt=""
          /></a>
          <button type="button" class="search-btn">
            <img class="search" src="/static/images/search.png" alt="" />
          </button>
        </div>
      </header>


<div class="gallery-section">
      <div class="galleries sliders">
        <div class="gallery">
          <div class="about-img" style="background: url('/static/images/1.jpg'); width: 100%; height: 70vh; background-position: center; background-size: cover;">

          </div>
        </div>
      </div>
      <br>
      <br>

      <p class="gallery-para">
        Индийская и Китайская плитка — древнейший материал, история которого берет свое начало в IX веке. Мы предлагаем самые широкий спектр плиток и кафелей для творчества и создания красивых интерьеров из итальянской плитки в Узбекистане. Если итальянская плитка – то только Demar!
      </p>

      <div style="text-align: center">
        <a href="{% url 'main:gallery' %}"><button type="button" class="gallery-btn">Подробнее</button></a>
      </div>
    </div>


   <div class="footer-section">
      <div class="footers">
        <div class="footer-left">
          <img class="logofooter" src="/static/images/ащщеукдщпщ.png" alt="" />
          <h6 class="copy">©Demar 2022</h6>
        </div>
        <div class="footer-center">
          <h1 class="footer-text"><a style="color: #fff;" href="{% url 'main:contact' %}">Контакт</a></h1>
          <h1 class="footer-text"><a style="color: #fff;" href="{% url 'main:gallery' %}">Галерея</a></h1>
          <h1 class="footer-text">
            <a style="color: #fff;" href="{% url 'main:laminat' %}">Ламинат/Паркет</a>
          </h1>
          <h1 class="footer-text"><a style="color: #fff; " href="{% url 'main:plitki' %}"> Кафель </a></h1>
        </div>
        <div class="footer-right">
          <h2 class="footer-phone">+998 (99) 555-25-89</h2>
          <div class="footer-left-first">
            <h2 class="footer-title">Адрес</h2>
            <h6 class="footer-para">Чиланзарский район, 8 улица Аль-Хорезми</h6>
          </div>
          <div>
            <h2 class="footer-title">E-mail</h2>
            <h6 class="footer-para">Demar.support.gmail.com</h6>
          </div>
        </div>
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-google-plus"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
      </div>
    </div>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="/static/script.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
      </body>
</html>
{% endblock %}

templates/cart.html
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="/static/fontawesome-free-5.15.4-web/css/all.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Cart</title>
    <link rel="stylesheet" href="/static/css/cart.css" />
  </head>
  <body>
    <header id="navbar">
      <a href="{% url 'main:index' %}"><img class="logo" src="/static/images/logo.png" alt="" /></a> 
        <div class="btn-hamburger" id="burger">
          <div id="drop-men" class="dropdown">
            <a data-toggle="dropdown"><i class="fas fa-bars"></i></a>
            <ul
              style="background-color: black; margin-left: -10px"
              id="drop-menu"
              class="dropdown-menu"
              role="menu"
              aria-labelledby="dLabel"
            >
                <div class="dropdow">
                <li><a href="{% url 'main:contact' %}">Контакты</a></li>
              </div><div class="dropdow">
                <li><a href="{% url 'main:about' %}">О нас</a></li>
              </div>
              <hr />
              <div class="dropdow">
                <li><a href="{% url 'main:gallery' %}">Галерея</a></li>
              </div>
            </ul>
          </div>
        </div>
        <ul class="header" id="ul">
          <li><a href="{% url 'main:contact' %}">Контакты</a></li>
          <li><a href="{% url 'main:gallery' %}">Галерея</a></li>
          <li><a href="{% url 'main:about' %}"> О нас</a></li>

        </ul>
        <div class="li-cen">
          <li class="glry">
            <div class="dropdown">
              <a style="color: #fff;"class="dropdown-toggle" data-toggle="dropdown">Каталог</a>
              <ul
                id="dropdown-menu"
                class="dropdown-menu"
                role="menu"
                aria-labelledby="dLabel"
              >
                <div class="dropdowns">
                  <h1 class="stoness"><a style="color: black;" href="{% url 'main:plitki' %}">Плитки</a></h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/stones.png"
                    alt=""
                  />
                </div>
                <hr class="hri" />
                <div class="dropdowns">
                  <h1 class="laminate">
                    <a style="color: black;" href="{% url 'main:laminat' %}">Пракет/ламинат</a>
                  </h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/laminates.png"
                    alt=""
                  />
                </div>
              </ul>
            </div>
          </li>
        </div>
        <div class="navbar-end">
          <a href="{% url 'main:cart' %}"
            ><img class="cart" src="/static/images/cart.png" alt=""
          /></a>
          <button type="button" class="search-btn">
            <img class="search" src="/static/images/search.png" alt="" />
          </button>
        </div>
      </header>

    <div class="white">
      <button type="button" class="clear-btn">
        <img class="cleo" src="/static/images/clear.png" alt="" />
      </button>
      <div class="white-div">
        <input type="text" class="white-input" />
      </div>
      <h1 class="white-text">Найдено (0)</h1>
    </div>

    <div class="cart-section">
      <h2 class="cart-text">Моя корзина</h2>
      <h6 class="cart-title">
        В корзине <span style="color: #f5b282">{{cart.carts.all.count}} товаров</span>
      </h6>
      <div class="carts">
        
        {% for carts in cart.carts.all %}
        <div class="carte">
          <div class="cart-cart">
            <div class="cartes" style="margin-top: 39px">
              <img class="stone" src="{{carts.product.image.url}}" alt="" />
              <h1 class="cart-cart-text">{{carts.product.name}}</h1>
            </div>
            <div>
              <button type="button" class="delete" data-id="{{carts.id}}"><img class="krestik" src="/static/images/clear.png" alt="" /></button>
            </div>
          </div>
          <div class="cart-in">
            <div>
              <h4 class="cart-in-text">Цена (m2)</h4>
              <h4 class="cart-in-title">{{carts.product.price}} сум</h4>
            </div>
          </div>
          <div class="cart-on">
            <div style="margin-right: 40px">
              <h4 class="cart-on-text">Количество (m2)</h4>
              <div style="display: flex">
                <input data-id="{{carts.id}}" type="number" class="mkv" value="{{carts.mkv}}">
                <h6 style="margin-left: 20px;"> Итого:</h6>
                <h4 class="cart-on-title"><b class="price">{{carts.all_price}}</b> сум</h4>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
          
        
        
      </div>
      <div class="all-price">Итого: <b class="all">{{cart.all_price}}</b> сум</div>
      <div style="text-align: center">
        <a href="{% url 'main:orderview' %}"><button type="button" class="cart-btn">Оформить заказ</button></a>
      </div>
    </div>

    <div class="mapouter">
  <div class="gmap_canvas">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d5999.3963544126!2d69.18994!3d41.250132!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xfad5642e5694a55a!2zNDHCsDE1JzAwLjUiTiA2OcKwMTEnMjMuOCJF!5e0!3m2!1sru!2s!4v1645291422672!5m2!1sru!2s" width="1348" height="1024" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

    </a>
    <br>

    </div>
  </div>
       <<div class="footer-section">
      <div class="footers">
        <div class="footer-left">
          <img class="logofooter" src="/static/images/ащщеукдщпщ.png" alt="" />
          <h6 class="copy">©Demar 2022</h6>
        </div>
        <div class="footer-center">
          <h1 class="footer-text"><a style="color: #fff;" href="{% url 'main:contact' %}">Контакт</a></h1>
          <h1 class="footer-text"><a style="color: #fff;" href="{% url 'main:gallery' %}">Галерея</a></h1>
          <h1 class="footer-text">
            <a style="color: #fff;" href="{% url 'main:laminat' %}">Ламинат/Паркет</a>
          </h1>
          <h1 class="footer-text"><a style="color: #fff; " href="{% url 'main:plitki' %}"> Кафель </a></h1>
        </div>
         <div class="footer-right">
          <h2 class="footer-phone">+998 (99) 400-07-70</h2>
          <div class="footer-left-first">
            <h2 class="footer-title">Адрес</h2>
            <h6 class="footer-para">Чиланзарский район, 8 улица Аль-Хорезми</h6>
          </div>
          <div>
            <h2 class="footer-title">E-mail</h2>
            <h6 class="footer-para">Demar.support.gmail.com</h6>
          </div>
        </div>
          <a href="https://www.facebook.com/DemarPlus/?ti=as"><i class="fa fa-facebook"></i></a>
          <a href="https://www.google.com/demar.uz"><i class="fa fa-google-plus"></i></a>
          <a href="https://www.instagram.com/demar_plus"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
      </div>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
  </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script src="/static/script.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
  </body>
</html>
{% endblock%}